import jsImg from "../assets/images/js.jpeg";
import reactImg from "../assets/images/react.jpeg";
import nodeJsImg from "../assets/images/nodeJs.jpeg";
import bootstrapImg from "../assets/images/bootstrap.jpeg";
import reactLibrariesImg from "../assets/images/reactLibraries.jpeg";
import nextJsImg from "../assets/images/nextJs.jpeg";
import gitHubImg from "../assets/images/gitHub.jpeg";
import npmImg from "../assets/images/npm.jpeg";
import cssImg from "../assets/images/css.jpeg";
import htmlImg from "../assets/images/html.jpeg";
import flexBoxImg from "../assets/images/flexBox.jpeg";

const coursesList = [
  {
    id: 1,
    title: "Comprehensive JavaScript course",
    desc: "Master the fundamentals and advanced concepts of JavaScript, the most popular programming language for web development.",
    price: 79.99,
    discount: 0,
    time: "60 hour",
    lastUpdate: "2024/2/1",
    prerequisites: "HTML & CSS",
    courseStatus: "Completed",
    courseInfo: "Course Description...",
    img: jsImg,
    teacher: {
      name: "Sara Mohammadi",
      img: "/images/teachers/sara.jpg",
      bio: "Senior frontend developer with over 8 years of experience in web development, specialized in JavaScript frameworks.",
    },
    seasons: [
      {
        id: 1,
        title: "Introduction to JS",
        sessions: [
          {id: 1, title: "What is JavaScript?", duration: "10:00" },
          {id: 2, title: "Variables and Data Types", duration: "15:00" },
        ],
      },
      {
        id: 2,
        title: "DOM & Events",
        sessions: [
          {id: 1, title: "DOM Manipulation", duration: "18:00" },
          {id: 2, title: "Event Handling", duration: "20:00" },
        ],
      },
    ],
    comments: [
      {
        name: "Ali Rezaei",
        email: "ali@email.com",
        date: "2025/06/01",
        comment: "One of the best JS courses I've taken!",
        responses: [
          {
            name: "Sara Mohammadi",
            date: "2025/06/02",
            comment: "Thanks Ali! Happy to hear that.",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Commonly used React libraries",
    desc: "Explore essential React libraries that enhance productivity and simplify development.",
    price: 58.69,
    discount: 0,
    time: "15 hour",
    lastUpdate: "2025/4/12",
    prerequisites: "React",
    courseStatus: "In holding",
    courseInfo: "This course introduces...",
    img: reactLibrariesImg,
    teacher: {
      name: "Reza Ghanbari",
      img: "/images/teachers/reza.jpg",
      bio: "React expert and open-source contributor with deep knowledge of the React ecosystem.",
    },
    seasons: [
      {
        id: 1,
        title: "State Management",
        sessions: [
          {id: 1, title: "Redux Toolkit", duration: "20:00" },
          {id: 2, title: "Zustand", duration: "25:00" },
        ],
      },
    ],
    comments: [],
  },
  {
    id: 3,
    title: "Comprehensive React course",
    desc: "Master modern web development with React – a powerful JavaScript library for building user interfaces.",
    price: 99.99,
    discount: 20,
    time: "50 hour",
    lastUpdate: "2024/10/12",
    prerequisites: "JS",
    courseStatus: "Completed",
    courseInfo: "This course offers a deep dive into React...",
    img: reactImg,
    teacher: {
      name: "Amin Hosseini",
      img: "/images/teachers/amin.jpg",
      bio: "Frontend instructor and UI/UX specialist with 6+ years of experience.",
    },
    seasons: [
      {
        id: 1,
        title: "React Basics",
        sessions: [
          {id: 1, title: "JSX & Components", duration: "18:00" },
          {id: 2, title: "Props & State", duration: "22:00" },
        ],
      },
      {
        id: 2,
        title: "Hooks",
        sessions: [{id: 1, title: "useEffect & useContext", duration: "30:00" }],
      },
    ],
    comments: [],
  },
  {
    id: 4,
    title: "Complete node.js course",
    desc: "Learn to build backend services and APIs using Node.js and Express.",
    price: 150.79,
    discount: 25,
    time: "120 hour",
    lastUpdate: "2024/5/12",
    prerequisites: "JS",
    courseStatus: "In holding",
    courseInfo: "Dive into server-side development...",
    img: nodeJsImg,
    teacher: {
      name: "Shayan Gholami",
      img: "/images/teachers/shayan.jpg",
      bio: "Full-stack developer specialized in scalable backend systems.",
    },
    seasons: [
      {
        id: 1,
        title: "Intro to Node.js",
        sessions: [
          {id: 1, title: "Installing Node", duration: "15:00" },
          {id: 2, title: "Node Modules", duration: "20:00" },
        ],
      },
    ],
    comments: [],
  },
  {
    id: 5,
    title: "Next.js project-based training",
    desc: "Learn to build fast, SEO-friendly full-stack applications using Next.js.",
    price: 39.99,
    discount: 0,
    time: "20 hour",
    lastUpdate: "2024/1/15",
    prerequisites: "JS & React",
    courseStatus: "In holding",
    courseInfo: "Next.js is a powerful React-based framework...",
    img: nextJsImg,
    teacher: {
      name: "Niloofar Tavakoli",
      img: "/images/teachers/niloofar.jpg",
      bio: "Web developer and Next.js specialist with expertise in SEO and full-stack design.",
    },
    seasons: [
      {
        id: 1,
        title: "Pages & Routing",
        sessions: [{ title: "File-based routing", duration: "12:00" }],
      },
    ],
    comments: [],
  },
  {
    id: 6,
    title: "npm training course",
    desc: "Master npm – the package manager every JavaScript developer needs to know.",
    price: 28.5,
    discount: 3,
    time: "6 hour",
    lastUpdate: "2025/2/22",
    prerequisites: "JS",
    courseStatus: "Completed",
    courseInfo: "npm (Node Package Manager)...",
    img: npmImg,
    teacher: {
      name: "Kian Parvaneh",
      img: "/images/teachers/kian.jpg",
      bio: "Open-source contributor and tooling engineer with a passion for package management.",
    },
    seasons: [],
    comments: [],
  },
  {
    id: 7,
    title: "Bootstrap project-based course",
    desc: "Build responsive websites quickly using the Bootstrap CSS framework.",
    price: 30,
    discount: 5,
    time: "3 hour",
    lastUpdate: "2023/11/24",
    prerequisites: "CSS & HTML & Flex Box",
    courseStatus: "Completed",
    courseInfo: "Bootstrap is a leading CSS framework...",
    img: bootstrapImg,
    teacher: {
      name: "Farid Nikzad",
      img: "/images/teachers/farid.jpg",
      bio: "UI engineer focused on responsive and mobile-first design using frameworks.",
    },
    seasons: [],
    comments: [],
  },
  {
    id: 8,
    title: "Learning to work with git and github",
    desc: "Understand version control and collaboration using Git and GitHub.",
    price: 40,
    discount: 5.01,
    time: "12 hour",
    lastUpdate: "2025/1/12",
    prerequisites: "Coding & programming language",
    courseStatus: "Completed",
    courseInfo: "This course teaches the fundamental...",
    img: gitHubImg,
    teacher: {
      name: "Azadeh Rad",
      img: "/images/teachers/azadeh.jpg",
      bio: "DevOps specialist and GitHub power user helping developers collaborate better.",
    },
    seasons: [],
    comments: [],
  },
  {
    id: 9,
    title: "Project-based CSS training",
    desc: "Learn how to style professional websites with CSS through hands-on projects.",
    price: 0,
    discount: 0,
    time: "30 hour",
    lastUpdate: "2025/3/4",
    prerequisites: "HTML",
    courseStatus: "Completed",
    courseInfo: "This course teaches you CSS from the ground up...",
    img: cssImg,
    teacher: {
      name: "Milad Dori",
      img: "/images/teachers/milad.jpg",
      bio: "CSS specialist with strong background in scalable design systems.",
    },
    seasons: [],
    comments: [],
  },
  {
    id: 10,
    title: "HTML Basics Tutorial",
    desc: "Learn the fundamentals of web development with this beginner-friendly HTML course.",
    price: 0,
    discount: 0,
    time: "5 hour",
    lastUpdate: "2024/5/4",
    prerequisites: "NONE",
    courseStatus: "Completed",
    courseInfo: "This course introduces HTML — the foundation...",
    img: htmlImg,
    teacher: {
      name: "Laleh Nouri",
      img: "/images/teachers/laleh.jpg",
      bio: "Beginner-level instructor passionate about teaching web basics.",
    },
    seasons: [],
    comments: [],
  },
  {
    id: 11,
    title: "FlexBox Project-Based Course",
    desc: "Master layout design with CSS Flexbox by building practical components.",
    price: 20.49,
    discount: 2,
    time: "12 hour",
    lastUpdate: "2025/3/12",
    prerequisites: "CSS & HTML",
    courseStatus: "Completed",
    courseInfo: "Flexbox is a powerful layout module in CSS...",
    img: flexBoxImg,
    teacher: {
      name: "Mehrdad Alavi",
      img: "/images/teachers/mehrdad.jpg",
      bio: "Layout design specialist and Flexbox expert helping devs structure UI effectively.",
    },
    seasons: [],
    comments: [],
  },
];

export default coursesList;
